# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
 push:
  branches: [ master ]
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i
      - run: ls -lrt node_modules
      - name: 'Tar files'
        run: tar -cvf node_modules.tar node_modules/
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
         name: node_modules
         path: node_modules.tar  
      - run: ls -lrt

  build1:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3     
      - name: Unstash Go Build
        uses: actions/download-artifact@v3
        with:
          name:  node_modules
      - name: 'un Tar files'
        run: tar -xvf node_modules.tar 
      - run: |
         ls -lrt
         ls -lrt node_modules


